[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "menglab"  
version = "0.1.0"
description = "Utilities for loading molecular boiling-point datasets with RDKit descriptors"
readme = "README.md"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
license = { text = "MIT" }
requires-python = ">=3.9"

dependencies = [
    "numpy>=1.23",
    "pandas>=1.5",
    "requests>=2.28",
    "pyreadr>=0.4",
    # RDKit: official wheels are distributed under "rdkit-pypi"
    "rdkit-pypi>=2022.9",
]

[project.urls]
Homepage = "https://github.com/SorenKyhl/MENG15100"
Issues = "https://github.com/SorenKyhl/MENG15100/issues"
Source = "https://github.com/SorenKyhl/MENG15100"

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*", "examples*"]
